drop table if exists firstnames;
create TEMPORARY TABLE firstnames
	(val varchar(50));

insert into firstnames (val) VALUES 
('Mary'),
('Patricia'),
('Linda'),
('Barbara'),
('Elizabeth'),
('Jennifer'),
('Maria'),
('Susan'),
('Margaret'),
('Dorothy'),
('Lisa'),
('Nancy'),
('Karen'),
('Betty'),
('Helen'),
('Sandra'),
('Donna'),
('Carol'),
('Ruth'),
('Sharon'),
('Michelle'),
('Laura'),
('Sarah'),
('Kimberly'),
('Deborah'),
('Jessica'),
('Shirley'),
('Cynthia'),
('Angela'),
('Melissa'),
('Brenda'),
('Amy'),
('Anna'),
('Rebecca'),
('Virginia'),
('Kathleen'),
('Pamela'),
('Martha'),
('Debra'),
('Amanda'),
('Stephanie'),
('Carolyn'),
('Christine'),
('Marie'),
('Janet'),
('Catherine'),
('Frances'),
('Ann'),
('Joyce'),
('Diane'),
('Alice'),
('Julie'),
('Heather'),
('Teresa'),
('Doris'),
('Gloria'),
('Evelyn'),
('Jean'),
('Cheryl'),
('Mildred'),
('Katherine'),
('Joan'),
('James'),
('John'),
('Robert'),
('Michael'),
('William'),
('David'),
('Richard'),
('Charles'),
('Joseph'),
('Thomas'),
('Christopher'),
('Daniel'),
('Paul'),
('Mark'),
('Donald'),
('George'),
('Kenneth'),
('Steven'),
('Edward'),
('Brian'),
('Ronald'),
('Anthony'),
('Kevin'),
('Jason'),
('Matthew'),
('Gary'),
('Timothy'),
('Jose'),
('Larry'),
('Jeffrey'),
('Frank'),
('Scott'),
('Eric'),
('Stephen'),
('Andrew'),
('Raymond'),
('Gregory'),
('Joshua'),
('Jerry'),
('Dennis'),
('Walter'),
('Patrick'),
('Peter'),
('Harold'),
('Douglas'),
('Henry'),
('Carl'),
('Arthur'),
('Ryan'),
('Roger'),
('Joe'),
('Juan'),
('Jack'),
('Albert'),
('Jonathan'),
('Justin'),
('Terry'),
('Gerald'),
('Keith'),
('Samuel'),
('Willie'),
('Ralph'),
('Lawrence'),
('Nicholas'),
('Roy'),
('Benjamin'),
('Bruce');

drop table if exists lastnames;
create TEMPORARY TABLE lastnames
	(val varchar(50));

insert into lastnames (val) VALUES 
('Smith'),
('Johnson'),
('Williams'),
('Jones'),
('Brown'),
('Davis'),
('Miller'),
('Wilson'),
('Moore'),
('Taylor'),
('Anderson'),
('Thomas'),
('Jackson'),
('White'),
('Harris'),
('Martin'),
('Thompson'),
('Garcia'),
('Martinez'),
('Robinson'),
('Clark'),
('Rodriguez'),
('Lewis'),
('Lee'),
('Walker'),
('Hall'),
('Allen'),
('Young'),
('Hernandez'),
('King'),
('Wright'),
('Lopez'),
('Hill'),
('Scott'),
('Green'),
('Adams'),
('Baker'),
('Gonzalez'),
('Nelson'),
('Carter'),
('Mitchell'),
('Perez'),
('Roberts'),
('Turner'),
('Phillips'),
('Campbell'),
('Parker'),
('Evans'),
('Edwards'),
('Collins'),
('Stewart'),
('Sanchez'),
('Morris'),
('Rogers'),
('Reed'),
('Cook'),
('Morgan'),
('Bell'),
('Murphy'),
('Bailey'),
('Rivera'),
('Cooper'),
('Richardson'),
('Cox'),
('Howard'),
('Ward'),
('Torres'),
('Peterson'),
('Gray'),
('Ramirez'),
('James'),
('Watson'),
('Brooks'),
('Kelly'),
('Sanders'),
('Price'),
('Bennett'),
('Wood'),
('Barnes'),
('Ross'),
('Henderson'),
('Coleman'),
('Jenkins'),
('Perry'),
('Powell'),
('Long'),
('Patterson'),
('Hughes'),
('Flores'),
('Washington'),
('Butler'),
('Simmons'),
('Foster'),
('Gonzales'),
('Bryant'),
('Alexander'),
('Russell'),
('Griffin'),
('Diaz'),
('Hayes'),
('Myers'),
('Ford'),
('Hamilton'),
('Graham'),
('Sullivan'),
('Wallace'),
('Woods'),
('Cole'),
('West'),
('Jordan'),
('Owens'),
('Reynolds'),
('Fisher'),
('Ellis'),
('Harrison'),
('Gibson'),
('Mcdonald'),
('Cruz'),
('Marshall'),
('Ortiz'),
('Gomez'),
('Murray'),
('Freeman'),
('Wells'),
('Webb'),
('Simpson'),
('Stevens'),
('Tucker'),
('Porter'),
('Hunter'),
('Hicks'),
('Crawford'),
('Henry'),
('Boyd'),
('Mason'),
('Morales'),
('Kennedy'),
('Warren'),
('Dixon'),
('Ramos'),
('Reyes'),
('Burns'),
('Gordon'),
('Shaw'),
('Holmes'),
('Rice'),
('Robertson'),
('Hunt');

drop table if exists phone_nums;
create TEMPORARY TABLE phone_nums
	(val varchar(50));

insert into phone_nums (val) VALUES 
("111-111-1111"),
("222-222-2222"),
("333-333-3333"),
("444-444-4444"),
("555-555-5555"),
("666-666-6666"),
("777-777-7777"),
("888-888-8888"),
("999-999-9999");

drop table if exists phone_nums2;
create TEMPORARY TABLE phone_nums2
	(val varchar(50));

insert into phone_nums2 (val) VALUES 
("111-111-1111"),
("222-222-2222"),
("333-333-3333"),
("444-444-4444"),
("555-555-5555"),
("666-666-6666"),
("777-777-7777"),
("888-888-8888"),
("999-999-9999");


update user set 
firstname = (select val from firstnames order by rand() limit 1), 
lastname = (select val from lastnames order by rand() limit 1),
telephone_1 = (select val from phone_nums order by rand() limit 1),
telephone_2 = (select val from phone_nums2 order by rand() limit 1);

drop table if exists street_nums;
create TEMPORARY TABLE street_nums
	(val varchar(50));

insert into street_nums (val) VALUES 
("12"),
("15678"),
("233"),
("4563"),
("2222"),
("19271"),
("129"),
("11111"),
("223");


drop table if exists street_names;
create TEMPORARY TABLE street_names
	(val varchar(50));

insert into street_names (val) VALUES 
("3rd"),
("4th"),
("Oak"),
("Elm"),
("Main"),
("255th"),
("1st"),
("Sad Sack"),
("Caviar"),
('Lachance'),
('Keaton'),
('Israel'),
('Ferrara'),
('Falcon'),
('Clemens'),
('Blocker'),
('Applegate'),
('Paz'),
('Needham'),
('Mojica'),
('Kuykendall');


drop table if exists street_types;
create TEMPORARY TABLE street_types
	(val varchar(50));

insert into street_types (val) VALUES 
("ST"),
("street"),
("Ave"),
("AV"),
("Avenue"),
("Blvd"),
("Way");

drop table if exists street_dirs;
create TEMPORARY TABLE street_dirs
	(val varchar(50));
insert into street_dirs (val) VALUES 
("N"),
("S"),
("E"),
("W"),
("SE"),
("SW"),
("NE");

update address set 
address_line1 = CONCAT((select val from street_nums order by rand() limit 1), " ", 
											(select val from street_names order by rand() limit 1), " ",
											(select val from street_types order by rand() limit 1), " ",
											(select val from street_dirs order by rand() limit 1));

